# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idea?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: "123456"

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.example.demo.model
server:
  port: 9000